[compile]
target = "aarch64-unknown-none"

[compile.build.Custom]
# 编译命令，可多条
shell = ["make ARCH=aarch64 A=examples/helloworld FEATURES=page-alloc-4g"]
# 要启动的内核
kernel = "examples/helloworld/helloworld_aarch64-qemu-virt.bin"

[qemu]
machine = "virt"
cpu = "cortex-a57"
graphic = false
args = ""