#
# HardWare Board configuration
#
[board]
# The board name
name = "phytiumpi"
# Architecture identifier.
arch = "aarch64" 

#
# OS Tool configuration
#
[ostool]
# The buad rate of serial console
baud_rate = 115200
# The serial console device
serial = "/dev/ttyUSB1"
# The path of axvisor image
kernel = "path/axvisor_aarch64-phytiumpi.bin"
# The path of the device tree blob (DTB)
dtb_file = "path/phytiumpi.dtb"

#
# Virtual Machine configuration
#
[vms]
path = "config/build/phytiumpi-linux/linux-qemu-aarch64.toml"