#
# HardWare Board configuration
#
[board]
# The board name
name = "rk3568"
# Architecture identifier.
arch = "aarch64" 

#
# OS Tool configuration
#
[ostool]
# The buad rate of serial console
baud_rate = 1500000
# The serial console device
serial = "/dev/ttyUSB2"
# The path of axvisor image
kernel = "path/axvisor_aarch64-rk3568.bin"
# The path of the device tree blob (DTB)
dtb_file = "path/rk3568.dtb"

#
# Virtual Machine configuration
#
[vms]
path = "config/build/rk3568-arceos/arceos-aarch64.toml"