#
# board configuration file
#
# The serial console device
serial = "/dev/ttyUSB1"
# The buad rate of serial console
baud_rate = 115200
# The path of the device tree blob (DTB)
dtb_file = "/home/runner/_work/axvisor/axvisor/axboard_test/config/phytiumpi-arceos/e2000.dtb"