#
# board configuration file
#
# The serial console device
serial = "/dev/ttyUSB0"
# The buad rate of serial console
baud_rate = 1500000
# The path of the device tree blob (DTB)
dtb_file = "/home/runner/_work/axvisor/axvisor/axboard_test/config/rk3568-arceos/rk3568.dtb"