[compile]
target = "aarch64-unknown-none"

[compile.build.Custom]
shell = ['./task.py build --plat aarch64-generic --arceos-args "LOG=info,SMP=4" --vmconfigs "axboard_test/config/rk3568-arceos/vm-arceos-rk3568.toml"']
kernel = "axvisor_test_aarch64-generic.bin"

[qemu]
machine = "virt"
cpu = "cortex-a57"
graphic = false
args = ""

include = ["./.board.toml"]
